version: '2'

services:
  jenkins:
    build: ./jenkins
    restart: always
    expose:
      - "8080"
      - "50000"
    volumes:
      - ./jenkins/jenkins_home:/var/jenkins_home

  sonarqube:
    image: sonarqube:5.1
    restart: always
    links:
        - db
    environment:
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=postgres123
      - SONARQUBE_JDBC_URL=jdbc:postgresql://database:5432/sonar
    ports:
      - "9000"
  db:
    image: postgres:9.5
    restart: always
    expose:
      - "5432"
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres123
    volumes:
        - sonar-volume:/var/lib/postgresql
        - ./sonar/init-sonar-db.sh:/docker-entrypoint-initdb.d/init-sonar-db.sh

volumes:
    sonar-volume:
        driver: local
