version: '2'

services:
  nginx:
    build: ./nginx
    restart: always
    links:
      - sonarqube
      - jenkins
    ports:
      - "80:80"

  jenkins:
    build: ./jenkins
    restart: always
    expose:
      - "8080"
      - "50000"
    volumes:
      - ./jenkins/jenkins_home:/var/jenkins_home

  sonarqube:
    build: ./sonar
    links:
        - db
    environment:
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
    expose:
      - "9000"
      - "9092"
  db:
    image: postgres:9.5
    restart: always
    hostname: db
    expose:
      - "5432"
    volumes:
        - sonar-volume:/var/lib/postgresql
        - ./sonar/:/docker-entrypoint-initdb.d/

volumes:
    sonar-volume:
        driver: local
